name: Diagnostic tests
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Windows PowerShell 5.1
        shell: powershell
        run: .\tests\Run-Tests.ps1
      - name: PowerShell 7
        shell: pwsh
        run: .\tests\Run-Tests.ps1
